[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
chroma_curve = "HAB3yLmxe6aYjtFhn7bEv9QLeUVxjt8dhgRamUWLwzip"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
